server:
  port: 8080

spring:
  application:
    name: employee-management-system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_employee_management_system?serverTimezone=UTC&cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true
    username: root
    password: root
  jpa:
    #defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    #show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        #format_sql: true
  sql:
    init:
      #mode: always
      platform: mysql
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB
